language: go
go:
 - master

script:
- go test -v ./...

- go build -ldflags "-X main.version=$TRAVIS_TAG" -o cd-test-linux.sh -i .

deploy:
  provider: releases
  draft: true
  api_key:
    secure: 2230fef6e72986b165f99e8a32c8e06aba1518ee
  skip_cleanup: true
  file: $TRAVIS_BUILD_DIR/cd-test-linux.sh